### ISSUE TITLE
Cannot install anymore on macOS

### ISSUE THREAD

**Issue by ktf** [adriansev/jalien_py#10]
When running:

```bash
python3 -m venv --system-site-packages venv
. venv/bin/activate
python3 -m pip install --upgrade pip 'setuptools<=60.8.2'
ALIBUILD=1 python3 -m pip install --upgrade --no-binary=ali-bot 'git+https://github.com/adriansev/jalien_py@1.6.1' 
```

on macOS with the latest homebrew we now get:

```
(venv) alibuild@alibuildmac05 ~ % ALIBUILD=1 python3 -m pip install --upgrade --no-binary=ali-bot 'git+https://github.com/adriansev/jalien_py@1.6.1' 'ali-bot[ci] @ git+https://github.com/alisw/ali-bot@master#egg=ali-bot'
Collecting git+https://github.com/adriansev/jalien_py@1.6.1
  Cloning https://github.com/adriansev/jalien_py (to revision 1.6.1) to /private/var/folders/12/v2l4vkcn6vx7dfw_9vgbgbzc0000gn/T/pip-req-build-ko1zozno
  Running command git clone --filter=blob:none --quiet https://github.com/adriansev/jalien_py /private/var/folders/12/v2l4vkcn6vx7dfw_9vgbgbzc0000gn/T/pip-req-build-ko1zozno
  Running command git checkout -q 88a755c4c406b2f86edd9c1c67f1584e1bb2f07f
  Resolved https://github.com/adriansev/jalien_py to commit 88a755c4c406b2f86edd9c1c67f1584e1bb2f07f
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/Users/alibuild/venv/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/Users/alibuild/venv/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/Users/alibuild/venv/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2178, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

i guess something needs to be changed in one of the dependencies?

**Comment by adriansev** [comment]
for the record, a newer/latest setuptools was needed
